language: node_js
node_js:
  - "9"

sudo: false

cache:
  directories:
    - "node_modules"

before_script:
  - npm install -g gulp typescript tslint
  - npm install

script:
  gulp build
  # TODO(arthurhsu): Switch to gulp test once SauceLabs is integrated.

